# Generated by Django 3.2.4 on 2021-07-14 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('type', models.CharField(max_length=25)),
                ('breed', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
