# Generated by Django 3.2.4 on 2021-07-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='time',
            field=models.CharField(max_length=10),
        ),
    ]
