# Generated by Django 3.2.4 on 2021-07-15 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_visit_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Immunization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateField(verbose_name='Date of Immunization')),
                ('upToDate', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['type']},
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='animal',
            name='type',
            field=models.CharField(choices=[('C', 'Cat'), ('D', 'Dog'), ('O', 'Other'), ('R', 'Rabbit')], default='Dog', max_length=1),
        ),
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateField(verbose_name='Meet & Greet Date'),
        ),
    ]
