# Generated by Django 3.2.4 on 2021-07-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_animal_immunizations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='immunization',
            name='date',
        ),
        migrations.RemoveField(
            model_name='immunization',
            name='upToDate',
        ),
        migrations.AddField(
            model_name='immunization',
            name='type',
            field=models.CharField(choices=[('C', 'Cat'), ('D', 'Dog'), ('O', 'Other'), ('R', 'Rabbit')], default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='animal',
            name='type',
            field=models.CharField(choices=[('C', 'Cat'), ('D', 'Dog'), ('O', 'Other'), ('R', 'Rabbit')], default='D', max_length=1),
        ),
    ]
